# prometheus/prometheus.yml

global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  # Scrape configuration for the FastAPI application
  - job_name: 'fastapi'
    # metrics_path defaults to /metrics
    # scheme defaults to http
    static_configs:
      # The target is 'web' because that's the service name in docker-compose.yml
      # The port is 8000, as exposed by the FastAPI application
      - targets: ['web:8000']

